name: MainBranch

on:
  push:
    branches:    
      - main

jobs:
  build:
    name: MainBranchActions
    runs-on: windows-latest
    container:
      image: rabbitmq:3.7-management
      env:
        RABBITMQ_DEFAULT_USER: agent
        RABBITMQ_DEFAULT_PASS: agent123
      ports:
        - 9080:15672
        - 5772:5672
      options:
        --hostname my-rabbit
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Echo
      run: echo toimii
